// Categories
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORIES"
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
// Subcategories
export const ADD_NEW_SUBCATEGORY = "ADD_NEW_SUBCATEGORIES"
export const GET_CAT_SUBS = "GET_CAT_SUBS"
// Brands
export const ADD_NEW_BRAND = "ADD_NEW_BRAND"
export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
export const GET_ONE_BRAND = "GET_ONE_BRAND"
// Products
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_ONE_PRODUCTS = "GET_ONE_PRODUCTS"
export const GET_SAME_PRODUCT_CAT = "GET_SAME_PRODUCT_CAT"
export const ADD_NEW_PRODUCT = "ADD_NEW_PRODUCT"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
// Error
export const GET_ERROR = "GET_ERROR"